version: "3.8"
services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./stock_data.csv:/docker-entrypoint-initdb.d/stock_data.csv # Corrected mounting
      - postgres_data:/var/lib/postgresql/data # Persistent database storage
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
